return {

	Roles = {
		{
			Name = "AFO",
			Players = {},
			Teams = {},
			Groups = {
				-- SOFCOM
				{ 9813447, 1 },
				-- CFMP
				{ 9813507, 1 },
				-- CN Police
				{ 34470000, 1 },
				-- HPS
				{ 34583493, 2 },
				-- HRPD
				{ 34228433, 3 },
				-- OPP
				{ 15023799, 3 },
				-- RCMP
				{ 15023376, 243 },
			},
			DiscordRoles = {},
			Roles = { "Developer" },
		},
		{
			Name = "Admin",
			Players = {},
			Teams = {},
			Groups = { { 15012374, 4 } },
			DiscordRoles = {},
			Roles = { "Developer" },
		},
		{
			Name = "Mod",
			Players = {},
			Teams = {},
			Groups = { { 15012374, 2 } },
			DiscordRoles = {},
			Roles = {},
		},
		{
			Name = "Developer",
			Players = {},
			Teams = {},
			Groups = { { 34183152, 2 } },
			DiscordRoles = {},
			Roles = {},
		},
	},
}
